<div class="Menu_top_bar_area">
    <?php echo View::partial("menu_inicio") ?>
    <div id="menubtn"></div>
    <?php echo View::partial("nav_requisitos") ?>
</div>


            <section class="home-area" style="margin-top:20px;margin-bottom:20px">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3">
                            <?php echo View::partial("menu_prestamos") ?>
                        </div>
                        <div class="col-md-9">
                            <div class="about-right-content" style="padding-top:20px">
                                <div class="section-title">
                                    <h2>Requisitos</h2>
                                    
                                </div>
                                <div class="row">
                                  <div class="col-sm-5">
                                      <?php echo Html::img($requisito->img,"",'width="100%" style="margin-bottom:3px"') ?>
                                  </div>
                                  <div class="col-sm-7">
                                   <h4><?php echo $requisito->nombre ?></h4><br>
                                    <?php echo $requisito->texto ?>
                                
                                  </div>
                                </div>

                              
                            </div>
                        </div>
                    </div>
                </div> 
            </section>
  

<?php echo View::partial("plan"); ?>
<?php echo View::partial("footer") ?>