<?php $plan = Load::model("general")->find_by_id("1"); ?>
 <section class="referir-barra">
        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                    <div class="quote-text">
                        <?php echo Html::img("referido.jpg",'','width="80px" style="float:left;margin-right:20px"') ?>
                        <h3><?php echo $plan->texto_referir ?></h3>
                    </div>
                </div>
                <div class="col-sm-4 text-right">
                    <div class="Buttons-on-Dark">
                        <a href="#" class="button-three" data-toggle="modal" data-target="#Plan"><?php echo $plan->titulo_btn ?></a>
                    </div>
                </div>
            </div>
        </div>
</section>

       <div class="col-md-12 modal fade" id="Plan" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
           <div class="modal-dialog" style="background:#fff">
              <div class="modal-content" style="border-radius:0;background:#fff;border:0">
                    <div class="col-md-12 modal-header" style="background:#fff;border-top:3px solid #009245">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                        <h5 class="modal-title" id="myModalLabel"><?php echo $plan->texto_referir ?></h5>
                    </div>
                    <div class="col-md-12 modal-body" style="margin-top:0;background:#fff">
                        <?php echo Html::img($plan->img,'','width="100%"') ?>
                    </div>
                 
              </div>
           </div>
        </div>