<?php
require dirname(__FILE__) . '/php-excel.class.php';
$data = array();
$data[] = array(
  'Nombre completo', 'Telefono', 'E-Mail', 'Interesado en',
  'Como supo de nosotros');
foreach ($contactos as $key => $value) {
  $data[] = array(
    $value->nombre_completo,
    $value->telefono,
    $value->correo,
    $value->servicio,
    $value->como_supo
  );
}
$xls = new Excel_XML;
$xls->addWorksheet('Contactos', $data);
$xls->sendWorkbook('contactos-'.(new Date()).'.xls');
?>
