<div class="page static-page-tables">
  <div class="bg-light lter b-b wrapper-md mb-10">
    <form  action="" method="post">
      <div class="row">
        <div class="col-sm-12 col-xs-12">
          <h1 class="font-thin h3 m-0">Corporacion Pacifico</h1>
          <small class="text-muted">Bienvenido al administrador</small>
          <button id="export-btn" style="margin-top:-20px;float:right;"
            type="button" class="btn btn-raised btn-primary">
            <i class="fa fa-fw fa-file-excel-o"></i> Exportar</button>
        </div>
      </div>
        <div class="row">
            <div class="col-sm-2 col-xs-2">
                <select class="form-control" name="servicio">
                  <option value="">Todo Servicio</option>
                  <?php foreach ($servicios as $key => $value): ?>
                    <option <?php if(Input::post("servicio")==$value->id) echo "selected" ?> value="<?php echo $value->id?>"><?php echo $value->nombre?></option>
                  <?php endforeach; ?>
                </select>
            </div>
            <div class="col-sm-1 col-xs-1">
              <button style="margin-top: 25px;" type="submit" class="btn btn-raised btn-primary">
                <i class="fa fa-fw fa-filter"></i>
                Filtrar</button>
            </div>
        </div>
    </form>
  </div>
  <div class="row">
      <div class="col-md-12">
          <section class="boxs ">
              <div class="boxs-header dvd dvd-btm">
                  <h1 class="custom-font"><strong>Listado de </strong> Contactos</h1>
              </div>
              <div class="boxs-body p-0">
                  <div class="table-responsive">
                      <table class="table table-middle">
                          <thead>
                              <tr>
                                  <th>Nombre completo</th>
                                  <th>Telefono</th>
                                  <th>Correo</th>
                                  <th>Interesado en</th>
                                  <th>Como supo de nosotros</th>
                                  <th></th>
                              </tr>
                          </thead>
                          <tbody>
                              <?php foreach ($contactos as $value) {
                                  $servicio = NULL;
                                  foreach ($servicios as $value2){
                                    if($value2->id == $value->servicios_id){
                                      $servicio = $value2;
                                      break;
                                    }
                                  }
                                  echo '
                                  <tr>
                                  <td>'.$value->nombre_completo.'</td>
                                  <td>'.$value->telefono.'</td>
                                  <td>'.$value->correo.'</td>
                                  <td>'.$servicio->nombre.'</td>
                                  <td>'.$value->como_supo.'</td>
                                  <td class="btn-operation">
                                      '.Html::link(
                                      "admin/ver_contacto/$value->id",
                                      '<i class="fa fa-eye"></i>',
                                      'class="btn btn-sm btn-success"').'
                                      '.Js::link(
                                        "admin/eliminar_contacto/$value->id",
                                        '<span class="btn btn-sm btn-danger">
                                        <i class="fa fa-trash-o"></i></span>',
                                        "¿Esta segur@ que desea eliminar el contacto?").'
                                  </td>
                                  </tr>
                              ';
                              } ?>

                          </tbody>
                      </table>
                  </div>
              </div>
          </section>
      </div>
  </div>
</div>
<script type="text/javascript">
  $('#export-btn').on('click', function(){
    $('form').append('<input type="hidden" name="export" value="true">')
    $('form').submit()
    $('form input[name="export"]').remove()
  })
</script>
