        <div class="page profile-page" style="padding-bottom:0">
            <div class="pagecontent">
                <div class="row">
                     <div class="col-md-12"> 
                        <section class="boxs boxs-simple"> 
                            <div class="boxs-body p-0">
                                <div role="tabpanel"> 
                                    <ul class="nav nav-tabs tabs-dark-t" role="tablist">
                                        <li role="presentation"><a href="#general" aria-controls="general" role="tab" data-toggle="tab">Info de la empresa</a></li>
                                    </ul>
                                    
                                    <div class="tab-content">
                                         <div role="tabpanel" class="tab-pane active" id="general">
                                            <div class="wrap-reset">
                                                <?php echo Form::openMultipart(); ?>
                                                <form class="profile-settings">
                                                    <div class="row">
                                                        <div class="form-group col-md-12 legend">
                                                            <h4><strong>Info en</strong> Spanish</h4>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="form-group col-md-12">
                                                            <label for="first-name">Historia *</label>
                                                            <?php echo Form::textarea('empresa.historia','class="form-control" autofocus required') ?>
                                                        </div>
                                                        <div class="form-group col-md-12">
                                                            <label for="first-name">Mision *</label>
                                                            <?php echo Form::textarea('empresa.mision','class="form-control" required') ?>
                                                        </div>
                                                        <div class="form-group col-md-12">
                                                            <label for="first-name">Vision *</label>
                                                            <?php echo Form::textarea('empresa.vision','class="form-control" required') ?>
                                                        </div>

                                                    </div>
                        
                                                    <hr>

                                                    <div class="row">
                                                        <div class="form-group col-md-12 legend">
                                                            <h4><strong>Info en</strong> English</h4>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="form-group col-md-12">
                                                            <label for="first-name">Historia *</label>
                                                            <?php echo Form::textarea('empresa.historia_en','class="form-control" required') ?>
                                                        </div>
                                                        <div class="form-group col-md-12">
                                                            <label for="first-name">Mision *</label>
                                                            <?php echo Form::textarea('empresa.mision_en','class="form-control" required') ?>
                                                        </div>
                                                        <div class="form-group col-md-12">
                                                            <label for="first-name">Vision *</label>
                                                            <?php echo Form::textarea('empresa.vision_en','class="form-control" required') ?>
                                                        </div>

                                                    </div>
                                                    <hr>
                                                    


                                                    <?php echo Form::hidden('empresa.id') ?>
                                                    <div class="row">
                                                        <div class="col-sm-12">
                                                            <?php echo Html::link("admin/config","Cancelar","class='btn btn-raised btn-default'") ?>
                                                            <button type="submit" value="submit" class="btn btn-raised btn-primary">Editar</button>
                                                        </div>
                                                    </div>

                                                </form>
                                                <?php echo Form::close(); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>  
<script>
     CKEDITOR.replace( 'empresa[historia]' );
      CKEDITOR.replace( 'empresa[historia_en]' );
</script>