        <div class="page profile-page" style="padding-bottom:0">
            <div class="pagecontent"> 
                <div class="row">
                     <div class="col-md-12"> 
                        <section class="boxs boxs-simple"> 
                            <div class="boxs-body p-0">
                                <div role="tabpanel"> 
                                    <ul class="nav nav-tabs tabs-dark-t" role="tablist">
                                        <li role="presentation"><a href="#general" aria-controls="general" role="tab" data-toggle="tab">Nueva Sucursal</a></li>
                                    </ul>
                                    
                                    <div class="tab-content">
                                         <div role="tabpanel" class="tab-pane active" id="general">
                                            <div class="wrap-reset">
                                                <?php echo Form::openMultipart(); ?>
                                                <form class="profile-settings">
                                                    <div class="row">
                                                        <div class="form-group col-md-12 legend">
                                                            <h4><strong>Datos</strong> Sucursal en Spanish</h4>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="form-group col-md-12">
                                                            <label for="first-name">Nombre</label>
                                                            <?php echo Form::text('sucursales.nombre','class="form-control" autofocus') ?>
                                                        </div> 
                                                        <div class="form-group col-md-12">
                                                            <label for="last-name">Dirección</label>
                                                            <?php echo Form::textarea('sucursales.direccion','class="form-control"') ?>
                                                        </div>
                                                         <div class="form-group col-md-12">
                                                            <label for="last-name">Horario</label>
                                                            <?php echo Form::textarea('sucursales.horario','class="form-control"') ?>
                                                        </div>
                                                       

                                                    </div>
                                                    <div class="row">
                                                        <div class="form-group col-md-12 legend">
                                                            <h4><strong>Datos</strong> Sucursal en English</h4>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="form-group col-md-12">
                                                            <label for="first-name">Nombre</label>
                                                            <?php echo Form::text('sucursales.nombre_en','class="form-control"') ?>
                                                        </div> 
                                                        <div class="form-group col-md-12">
                                                            <label for="last-name">Dirección</label>
                                                            <?php echo Form::textarea('sucursales.direccion_en','class="form-control"') ?>
                                                        </div>
                                                         <div class="form-group col-md-12">
                                                            <label for="last-name">Horario</label>
                                                            <?php echo Form::textarea('sucursales.horario_en','class="form-control"') ?>
                                                        </div>
                                                       

                                                    </div>
                                                    <hr>
                                                      <div class="row">
                                                        <div class="form-group col-md-6">
                                                            <label for="first-name">Teléfonos fijos</label>
                                                            <?php echo Form::text('sucursales.telefonos','class="form-control"') ?>
                                                        </div>
                                                        <div class="form-group col-md-6">
                                                            <label for="last-name">Celular, Whatsapp</label>
                                                            <?php echo Form::text('sucursales.celular','class="form-control"') ?>
                                                        </div>
                                                    </div>
                                                   
                                                   
                                                    <hr>
                                                    <div class="row">
                                                        <div class="col-md-3" style="margin-bottom:20px">
                                                            <div class='custom-input-file'><?php echo Form::file('images',"","") ?>Imagen</div>
                                                        </div>
                                                         <div class="col-md-3" style="margin-bottom:20px">
                                                            <div class='custom-input-file'><?php echo Form::file('mapa',"","") ?>Imagen del mapa</div>
                                                        </div>
                                                    </div>                                                
                                                    <hr>
                                                    <div class="row">
                                                        <div class="col-md-12">
                                                            <?php echo Html::link("admin/sucursales","Cancelar","class='btn btn-raised btn-default'") ?>
                                                            <button type="submit" value="submit" class="btn btn-raised btn-primary">Guardar</button>
                                                        </div>
                                                    </div>
                                                </form>
                                                <?php echo Form::close(); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>  
