<div class="page static-page-tables"> 
            <!-- bradcome -->
            <div class="bg-light lter b-b wrapper-md mb-10">
                <div class="row">
                            <div class="col-sm-6 col-xs-12">
                                <h1 class="font-thin h3 m-0">Corporacion Pacifico</h1>
                                <small class="text-muted">Bienvenido al administrador</small>
                            </div>
                        </div>
                         <div class="row">
                    <div class="col-sm-12">
                        <?php echo Html::link("admin/agregar_promocion",'<i class="glyphicon glyphicon-plus"></i> Agregar Promociones','class="btn btn-raised btn-info fileinput-button"') ?>
                        <?php //echo Html::link("admin/categorias",' Listado Categorias','class="btn btn-raised btn-success fileinput-button"') ?>
                    </div>
                </div>
            </div>
            
            <!-- row -->
            <div class="row">
                <div class="col-md-12">
                    <section class="boxs ">
                        <div class="boxs-header dvd dvd-btm">
                            <h1 class="custom-font"><strong>Listado de </strong> Promociones</h1>
                            
                        </div>
                        <div class="boxs-body p-0">
                            <div class="table-responsive">
                                <table class="table table-middle">
                                    <thead>
                                        <tr>
                                      
                                            <th>Imagen</th>
                                            <th>Nombre</th>
                                            <th>Editar</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($promociones as $value) {
                              
                                            echo
                                            '
                                             <tr>
                                            <td>'.Html::img($value->img,"","width='100px' style='border-radius:0px !important'").'</td>
                                            <td>'.$value->nombre.'</td>
                                            <td class="btn-operation">
                                                '.Html::link("admin/editar_promocion/$value->id",'<i class="fa fa-edit"></i>','class="btn btn-sm btn-success"').'
                                                '.Js::link("admin/deletepromocion/$value->id",'<span class="btn btn-sm btn-danger"><i class="fa fa-trash-o"></i></span>',"¿Esta segur@ que desea eliminar esta promocion?").'    
                                            </td>
                                            </tr>
                                        ';
                                        } ?>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
