<?php
require dirname(__FILE__) . '/php-excel.class.php';
$data = array();
$data[] = array(
  'Nombre', 'Apellido', 'Correo','Correo2', 'Celular', 'Cedula',
  'Sexo', 'Servicio', 'Laboral', 'Salario', 'Monto deseado', 'Ocupacion',
  'Tiempo de servicio', 'Lugar de trabajo', 'Sucursal mas cercana');
foreach ($solicitudes as $key => $value) {
  $data[] = array(
    $value->nombre,
    $value->apellido,
    $value->correo,
    $value->correo2,
    $value->celular,
    $value->provincia.'-'.$value->letra.'-'.$value->folio.'-'.$value->asiento,
    $value->sexo,
    $value->servicio,
    $value->laboral,
    $value->salario,
    $value->monto_deseado,
    $value->ocupacion,
    $value->tiempo_servicio,
    $value->lugar_trabajo,
    $value->sucursal
  );
}
$xls = new Excel_XML;
$xls->addWorksheet('Solicitudes', $data);
$xls->sendWorkbook('solicitudes-'.(new Date()).'.xls');
?>
