<div class="page static-page-tables">
  <div class="bg-light lter b-b wrapper-md mb-10">
    <form  action="" method="post">
      <div class="row">
        <div class="col-sm-11 col-xs-11">
          <h1 class="font-thin h3 m-0">Corporacion Pacifico</h1>
          <small class="text-muted">Bienvenido al administrador</small>
        </div>
        <div class="col-sm-1 col-xs-1">
          <button id="export-btn" style="float:right;"
          type="button" class="btn btn-raised btn-primary">
          <i class="fa fa-fw fa-file-excel-o"></i> Exportar</button>
        </div>
      </div>
        <div class="row">
            <div class="col-sm-2 col-xs-6">
              <input name="search" class="form-control" value="<?php echo Input::post("search")?>" placeholder="Nombre, Apellido, Laboral...">
            </div>
            <div class="col-sm-2 col-xs-6">
              <select class="form-control" name="servicio">
                <option value="">Servicios *</option>
                <?php foreach ($servicios as $key => $value): ?>
                  <option <?php if (Input::post("servicio")==$value->nombre) echo 'selected' ?> value="<?php echo $value->nombre ?>"><?php echo $value->nombre ?></option>
                <?php endforeach; ?>
              </select>
            </div>
            <div class="col-sm-2 col-xs-6">
              <select class="form-control" name="sexo">
                <option value="">Sexos *</option>
                <option <?php if (Input::post("sexo")=='masculino') echo 'selected' ?> value="masculino">Masculino</option>
                <option <?php if (Input::post("sexo")=='femenino') echo 'selected' ?> value="femenino">Femenino</option>
              </select>
            </div>
            <div class="col-sm-2 col-xs-6">
              <select class="form-control" name="salario">
                <option value="">Salarios *</option>
                <option <?php if (Input::post("salario")=='$ 500') echo 'selected' ?> value="$ 500">$ 500</option>
                <option <?php if (Input::post("salario")=='$ 600') echo 'selected' ?> value="$ 600">$ 600</option>
                <option <?php if (Input::post("salario")=='$ 700') echo 'selected' ?> value="$ 700">$ 700</option>
                <option <?php if (Input::post("salario")=='$ 800') echo 'selected' ?> value="$ 800">$ 800</option>
                <option <?php if (Input::post("salario")=='$ 900') echo 'selected' ?> value="$ 900">$ 900</option>
                <option <?php if (Input::post("salario")=='$ 1,000') echo 'selected' ?> value="$ 1,000">$ 1,000</option>
                <option <?php if (Input::post("salario")=='$ 1,500') echo 'selected' ?> value="$ 1,500">$ 1,500</option>
                <option <?php if (Input::post("salario")=='$ 2,000') echo 'selected' ?> value="$ 2,000">$ 2,000</option>
                <option <?php if (Input::post("salario")=='$ 3,500') echo 'selected' ?> value="$ 3,500">$ 3,500</option>
                <option <?php if (Input::post("salario")=='$ 4,000 ó más') echo 'selected' ?> value="$ 4,000 ó más">$ 4,000 ó más</option>
              </select>
            </div>
            <div class="col-sm-2 col-xs-6">
              <input name="fecha" type="date" class="form-control" value="<?php echo Input::post("fecha")?>" placeholder="Fecha">
            </div>
            <div class="col-sm-2 col-xs-6">
              <button style="margin-top: 25px;float:right" type="submit" class="btn btn-raised btn-primary">
                <i class="fa fa-fw fa-search"></i>
                Buscar
              </button>
            </div>
        </div>
        <?php $conditions?>
    </form>
  <div class="row">
      <div class="col-md-12">
          <section class="boxs ">
              <div class="boxs-header dvd dvd-btm">
                <h1 class="custom-font"><strong>Listado de </strong> Solicitudes</h1>
                <h1 class="custom-font" style="float: right;"><strong><?php echo $solicitudes_count.' de '.$solicitudes_count_total ?></strong></h1>
              </div>
              <div class="boxs-body p-0">
                  <div class="table-responsive">
                      <table id="table-solicitudes" class="table table-middle">
                          <thead>
                              <tr>
                                  <th width="1px"></th>
                                  <th>Solicitante </th>
                                  <th>Laboral </th>
                                  <th>Salario $</th>
                                  <th>Monto deseado $</th>
                                  <th>Servicio </th>
                                  <th>Sexo </th>
                                  <th>Fecha </th>
                                  <th width="70px"></th>
                              </tr>
                          </thead>
                          <tbody>
                            <?php setlocale(LC_MONETARY, 'en_US'); ?>
                              <?php foreach ($solicitudes as $value) {
                                  echo '
                                  <tr>
                                  <td><label>'.$value->id.'</label></td>
                                  <td>'.$value->nombre.' '.$value->apellido.'</td>
                                  <td>'.$value->laboral.'</td>
                                  <td>'.($value->salario).'</td>
                                  <td>'.(money_format('%(#10n', $value->monto_deseado)).'</td>
                                  <td>'.$value->servicio.'</td>
                                  <td>'.$value->sexo.'</td>
                                  <td>'.(new DateTime($value->created_at))->format('d-m-Y').'</td>
                                  <td class="btn-operation">
                                      '.Html::link(
                                      "admin/ver_solicitud/$value->id",
                                      '<i class="fa fa-eye"></i>',
                                      'style="width:30px;padding:5px;" title="Ver" class="btn btn-sm btn-success"').'
                                      '.Js::link(
                                        "admin/eliminar_solicitud/$value->id",
                                        '<div class="btn btn-sm btn-danger" title="Eliminar" style="width:30px;padding:5px;">
                                        <i class="fa fa-trash-o"></i></div>',
                                        "¿Esta segur@ que desea eliminar esta solicitud?").'
                                  </td>
                                  </tr>
                              ';
                              } ?>

                          </tbody>
                      </table>
                  </div>
              </div>
          </section>
      </div>
  </div>
</div>
<script type="text/javascript">
  $('#export-btn').on('click', function(){
    $('form').append('<input type="hidden" name="export" value="true">')
    $('form').submit()
    $('form input[name="export"]').remove()
  })
  $(function() {
    const spanish = {
      sLengthMenu: 'Mostrar _MENU_ registros',
      sZeroRecords: 'No se encontraron resultados',
      sEmptyTable: 'Ningún dato disponible en esta tabla',
      sInfo: '_START_ a _END_ de _TOTAL_',
      sInfoEmpty: '0 al 0 de 0',
      sInfoFiltered: '(filtrado de un total de _MAX_ registros)',
      sInfoPostFix: '',
      sSearch: '<i class="fa fa-search placeholder-icon-table"></i>',
      searchPlaceholder: 'Buscar...',
      sUrl: '',
      sInfoThousands: '',
      sLoadingRecords: 'Cargando...',
      oPaginate: {
        sFirst: 'Primera',
        sLast: 'Ultima',
        sNext: 'Siguiente',
        sPrevious: 'Anterior'
      },
      oAria: {
        sSortAscending: ': Activar para ordenar la columna de manera ascendente',
        sSortDescending: ': Activar para ordenar la columna de manera descendente'
      }
    }
    $('#table-solicitudes').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": false,
      "autoWidth": true,
      language: spanish
    })
  })
</script>
<style media="screen">
  .paginate_button{
    color: #777 !important;
    cursor: pointer;
    padding: 10px !important;
  }
  .dataTables_paginate{
    float: none !important;
    text-align:center !important;
  }
</style>
