<div class="page static-page-tables">
  <div class="bg-light lter b-b wrapper-md mb-10">
      <div class="row">
        <div class="col-sm-12 col-xs-12">
          <h1 class="font-thin h3 m-0">Corporacion Pacifico</h1>
          <small class="text-muted">Bienvenido al administrador</small>
          <button id="export-btn" style="margin-top:-20px;float:right;"
            type="button" class="btn btn-raised btn-primary">
            <i class="fa fa-fw fa-file-excel-o"></i> Exportar</button>
        </div>
      </div>
      <div class="row">
        <form  action="" method="post">
          <div class="col-sm-2 col-xs-2">
              <select class="form-control" name="servicio">
                <option value="">Todo Servicio</option>
                <?php foreach ($servicios as $key => $value): ?>
                  <option <?php if(Input::post("servicio")==$value->id) echo "selected" ?> value="<?php echo $value->id?>"><?php echo $value->nombre?></option>
                <?php endforeach; ?>
              </select>
          </div>
          <div class="col-sm-2 col-xs-2">
              <select class="form-control" name="salario">
                <option value="">Todo Salario</option>
                <option <?php if(Input::post("salario") == "$ 500") echo "selected" ?> value="$ 500">$ 500</option>
                <option <?php if(Input::post("salario") == "$ 600") echo "selected" ?> value="$ 600">$ 600</option>
                <option <?php if(Input::post("salario") == "$ 700") echo "selected" ?> value="$ 700">$ 700</option>
                <option <?php if(Input::post("salario") == "$ 800") echo "selected" ?> value="$ 800">$ 800</option>
                <option <?php if(Input::post("salario") == "$ 900") echo "selected" ?> value="$ 900">$ 900</option>
                <option <?php if(Input::post("salario") == "$ 1,000") echo "selected" ?> value="$ 1,000">$ 1,000</option>
                <option <?php if(Input::post("salario") == "$ 1,500") echo "selected" ?> value="$ 1,500">$ 1,500</option>
                <option <?php if(Input::post("salario") == "$ 2,000") echo "selected" ?> value="$ 2,000">$ 2,000</option>
                <option <?php if(Input::post("salario") == "$ 3,500") echo "selected" ?> value="$ 3,500">$ 3,500</option>
                <option <?php if(Input::post("salario") == "$ 4,000 ó más") echo "selected" ?> value="$ 4,000 ó más">$ 4,000 ó más</option>
              </select>
          </div>
          <div class="col-sm-2 col-xs-2">
              <select class="form-control" name="laboral">
                <option value="">Todos Laborales</option>
                <option <?php if(Input::post("laboral") == "Fuerza Pública") echo "selected" ?> value="Fuerza Pública">Fuerza Pública</option>
                <option <?php if(Input::post("laboral") == "Educadores") echo "selected" ?> value="Educadores">Educadores</option>
                <option <?php if(Input::post("laboral") == "Jubilados") echo "selected" ?> value="Jubilados">Jubilados</option>
                <option <?php if(Input::post("laboral") == "Gobierno Central") echo "selected" ?> value="Gobierno Central">Gobierno Central</option>
                <option <?php if(Input::post("laboral") == "Entidades Autónomas y Semi-autónomas") echo "selected" ?> value="Entidades Autónomas y Semi-autónomas">Entidades Autónomas y Semi-autónomas</option>
                <option <?php if(Input::post("laboral") == "ACP") echo "selected" ?> value="ACP">ACP</option>
                <option <?php if(Input::post("laboral") == "Empresa Privada") echo "selected" ?> value="Empresa Privada">Empresa Privada</option>
                <option <?php if(Input::post("laboral") == "Independiente (micro empresarios)") echo "selected" ?> value="Independiente (micro empresarios)">Independiente (micro empresarios)</option>
              </select>
          </div>
          <div class="col-sm-2 col-xs-2">
              <select class="form-control" name="sucursal">
                <option value="">Toda Sucursal</option>
                <?php foreach ($sucursales as $key => $value): ?>
                  <option <?php if(Input::post("sucursal")==$value->id) echo "selected" ?> value="<?php echo $value->id?>"><?php echo $value->nombre?></option>
                <?php endforeach; ?>
              </select>
          </div>

          <div class="col-sm-1 col-xs-1">
            <button style="margin-top: 25px;" type="submit" class="btn btn-raised btn-primary">
              <i class="fa fa-fw fa-filter"></i>
              Filtrar</button>
          </div>
        </form>
      </div>
  </div>
  <div class="row">
      <div class="col-md-12">
          <section class="boxs ">
              <div class="boxs-header dvd dvd-btm">
                  <h1 class="custom-font"><strong>Listado de </strong> Solicitudes</h1>
              </div>
              <div class="boxs-body p-0">
                  <div class="table-responsive">
                      <table class="table table-middle">
                          <thead>
                              <tr>
                                  <th>Nombre</th>
                                  <th>Apellido</th>
                                  <th>Laboral</th>
                                  <th>Salario</th>
                                  <th>Monto deseado</th>
                                  <th>Servicio</th>
                                  <th></th>
                              </tr>
                          </thead>
                          <tbody>
                              <?php foreach ($solicitudes as $value) {
                                  $servicio = NULL;
                                  foreach ($servicios as $value2){
                                    if($value2->id == $value->servicios_id){
                                      $servicio = $value2;
                                      break;
                                    }
                                  }
                                  echo '
                                  <tr>
                                  <td>'.$value->nombre.'</td>
                                  <td>'.$value->apellido.'</td>
                                  <td>'.$value->laboral.'</td>
                                  <td>'.$value->salario.'</td>
                                  <td>'.$value->monto_deseado.'</td>
                                  <td>'.$servicio->nombre.'</td>
                                  <td class="btn-operation">
                                      '.Html::link(
                                      "admin/ver_solicitud/$value->id",
                                      '<i class="fa fa-eye"></i>',
                                      'class="btn btn-sm btn-success"').'
                                      '.Js::link(
                                        "admin/eliminar_solicitud/$value->id",
                                        '<span class="btn btn-sm btn-danger">
                                        <i class="fa fa-trash-o"></i></span>',
                                        "¿Esta segur@ que desea eliminar esta solicitud?").'
                                  </td>
                                  </tr>
                              ';
                              } ?>

                          </tbody>
                      </table>
                  </div>
              </div>
          </section>
      </div>
  </div>
</div>
<script type="text/javascript">
  $('#export-btn').on('click', function(){
    $('form').append('<input type="hidden" name="export" value="true">')
    $('form').submit()
    $('form input[name="export"]').remove()
  })
</script>
