<?php
require dirname(__FILE__) . '/php-excel.class.php';
$data = array();
$data[] = array(
  'Nombre', 'Apellido', 'Correo','Correo2', 'Celular', 'Provincia', 'Letra', 'Folio', 'Asiento',
  'Sexo', 'Servicio', 'Laboral', 'Salario', 'Monto deseado', 'Ocupacion',
  'Tiempo de servicio', 'Lugar de trabajo', 'Sucursal mas cercana', 'Fecha', 'Comentario');
foreach ($solicitudes as $key => $value) {
  $data[] = array(
    $value->nombre,
    $value->apellido,
    $value->correo,
    $value->correo2,
    $value->celular,
    $value->provincia,
    $value->letra,
    $value->folio,
    $value->asiento,
    $value->sexo,
    $value->servicio,
    $value->laboral,
    $value->salario,
    $value->monto_deseado,
    $value->ocupacion,
    $value->tiempo_servicio_anos.' años y '.$value->tiempo_servicio_meses.' meses',
    $value->lugar_trabajo,
    $value->sucursal,
    (new DateTime($value->created_at))->format('d-m-Y'),
    $value->comentario,
  );
}
$xls = new Excel_XML;
$xls->addWorksheet('Solicitudes', $data);
$xls->sendWorkbook('solicitudes-'.(new Date()).'.xls');
?>
