<div class="page profile-page" style="padding-bottom:0">
    <div class="pagecontent">
        <div class="row">
             <div class="col-md-12">
                <section class="boxs boxs-simple">
                    <div class="boxs-body p-0">
                        <div role="tabpanel">
                            <ul class="nav nav-tabs tabs-dark-t" role="tablist">
                              <li role="presentation">
                                <a href="<?php echo PUBLIC_PATH.'admin/contactos/' ?>">
                                  <i class="fa fa-fw fa-mail-reply"></i>
                                </a>
                              </li>
                                <li role="presentation"><a href="#general" aria-controls="general" role="tab" data-toggle="tab">
                                  Contacto de <?php echo $contactos->servicio ?></a>
                                </li>
                                <li role="presentation" style="float: right;">
                                  <a href="<?php echo PUBLIC_PATH.'admin/eliminar_contacto/'.$contactos->id ?>" aria-controls="general">
                                    Eliminar
                                  </a>
                                </li>
                                <li role="presentation" style="float: right;">
                                  <a href="<?php echo PUBLIC_PATH.'admin/exportar_contacto/'.$contactos->id ?>" aria-controls="general">
                                    Exportar
                                  </a>
                                </li>
                            </ul>
                            <div class="tab-content">
                                 <div role="tabpanel" class="tab-pane active" id="general">
                                      <div class="wrap-reset">
                                        <?php echo Form::open() ?>
                                        <div class="col-md-12" style="padding:5px;border-bottom:1px solid #525252;padding-bottom:10px;margin-bottom:10px">
                                           <h4 style="font-weight:700;margin-top:20px">Datos del contacto</h4>
                                         </div>
                                          <div class="row">
                                            <div class="form-group col-md-6">
                                                <label for="first-name">Nombre completo:</label>
                                                <?php echo Form::text('contactos.nombre_completo',array(
                                                  'class'=>'form-control',
                                                  'required'=>'true',
                                                  'disabled'=>'true',
                                                  'type'=>'text',
                                                  'placeholder'=>'Nombre  *'
                                                ));?>
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label for="first-name">Correo:</label>
                                                <?php echo Form::text('contactos.correo',array(
                                                  'class'=>'form-control',
                                                  'required'=>'true',
                                                  'disabled'=>'true',
                                                  'type'=>'text',
                                                  'placeholder'=>'Apellido *'
                                                ));?>
                                            </div>
                                          </div>
                                          <div class="row">
                                            <div class="form-group col-md-6">
                                                <label for="first-name">Telefono:</label>
                                                <?php echo Form::input('text', '',array(
                                                  'required'=>'true',
                                                  'disabled'=>'true',
                                                  'class'=>'form-control',
                                                  'placeholder'=>""
                                                ),
                                                $contactos->telefono
                                              );?>
                                            </div>
                                            <div class="form-group col-md-6">
                                                <label for="first-name">Interesado en:</label>
                                                <?php echo Form::input('text', '',array(
                                                  'required'=>'true',
                                                  'disabled'=>'true',
                                                  'class'=>'form-control',
                                                  'placeholder'=>"##"
                                                ),
                                                $contactos->servicio
                                              );?>
                                            </div>
                                          </div>
                                          <div class="row">
                                            <div class="form-group col-md-6">
                                                <label for="first-name">Como supo de nosotros:</label>
                                                <?php echo Form::text('contactos.como_supo',array(
                                                  'required'=>'true',
                                                  'disabled'=>'true',
                                                  'style'=>"margin-top:0",
                                                  'class'=>"form-control",
                                                  'placeholder'=>" como supo de nosotros *"
                                                ));?>
                                            </div>

                                            <div class="form-group col-md-6">
                                                <label for="first-name">Mensaje:</label>
                                                <?php echo Form::text('contactos.mensaje',array(
                                                  'required'=>'true',
                                                  'disabled'=>'true',
                                                  'style'=>"margin-top:0",
                                                  'class'=>"form-control",
                                                  'placeholder'=>"Mensaje*"
                                                ));?>
                                            </div>

                                          </div>
                                        </div>
                                      </div>
                                          <?php echo Form::close() ?>
                                      </div>
                                    </div>
                                 </div>
                            </div>
                        </div>
                </section>
            </div>
        </div>
    </div>
</div>
