<div class="page profile-page" style="padding-bottom:0">
    <div class="pagecontent">
        <div class="row">
             <div class="col-md-12">
                <section class="boxs boxs-simple">
                    <div class="boxs-body p-0">
                        <div role="tabpanel">
                            <ul class="nav nav-tabs tabs-dark-t" role="tablist">
                                <li role="presentation"><a href="#general" aria-controls="general" role="tab" data-toggle="tab">Video</a></li>
                            </ul>
                            <div class="tab-content">
                                 <div role="tabpanel" class="tab-pane active" id="general">
                                    <div class="wrap-reset">
                                        <?php echo Form::openMultipart(); ?>
                                        <form class="profile-settings">
                                            <div class="row">
                                                <div class="form-group col-sm-12">
                                                    <label for="first-name">Link del video *</label>
                                                    <input type="text" name="video[link]" value="<?php echo $video->link?>" autofocus class="form-control" required>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="form-group col-sm-12">
                                                    <label for="first-name">Link mas videos *</label>
                                                    <input
                                                    type="text" name="video[link_mas]"
                                                    value="<?php echo $video->link_mas?>" 
                                                    autofocus class="form-control" required>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="form-group col-sm-12">
                                                    <label for="first-name">Titulo *</label>
                                                    <input type="text" name="video[titulo]" value="<?php echo $video->titulo?>" autofocus class="form-control" required>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="form-group col-sm-12">
                                                    <label for="first-name">Texto *</label>
                                                    <textarea name="video[texto]" rows="8" required class="form-control" cols="80"><?php echo $video->texto?></textarea>
                                                </div>
                                            </div>
                                            <input type="hidden" name="video[id]" value="<?php echo $video->id?>">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <?php echo Html::link("admin/video","Cancelar","class='btn btn-raised btn-default'") ?>
                                                    <button type="submit" value="submit" class="btn btn-raised btn-primary">Guardar</button>
                                                </div>
                                            </div>
                                        </form>
                                        <?php echo Form::close(); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>

<script>
CKEDITOR.replace( 'general[bolsa]' );
CKEDITOR.replace( 'general[bolsa_en]' );
</script>
