<div class="Menu_top_bar_area">
    <?php echo View::partial("menu_inicio") ?>
    <div id="menubtn"></div>
    <?php echo View::partial("nav_blog") ?>
</div>
<section class="home-area" style="margin-top:20px;margin-bottom:20px">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3">
                            <?php echo View::partial("menu_prestamos") ?>
                        </div>
                        <div class="col-md-9">
                             <div class="about-right-content" style="padding-top:20px">
                                <div class="section-title">
                                    <h2>BLOGS</h2>
                                </div>
                                <?php foreach ($blogs as $blog): ?>
                                    <div class="col-md-4 <?php echo $blog->titulo ?>">
                                        <div class="single-news single-grid">
                                            <div class="news-thumb">
                                                <?php echo Html::img('upload/blogs/'.$blog->imagen, $blog->titulo , array('style'=>"min-height: 200px;")) ?>
                                                <div class="thumb-hover">
                                                    <?php echo Html::link("blogs/detalle/".$blog->id,Html::img("plus.png")) ?>
                                                </div>
                                            </div>
                                            <div style="background:#fff;padding:20px">
                                                <?php
                                                if(strlen($blog->titulo) >= 58){$titulo = substr($blog->titulo,0 ,57).'...';}else{$titulo = $blog->titulo;}
                                                echo Html::link("blogs/detalle/".$blog->id,'<h3 style="min-height:50px;">'.$titulo.'</h3>') ?>
                                                <div class="news-details">
                                                    <small>
                                                      <?php echo (new DateTime($blog->created_at))->format('d-m-Y') ?>
                                                    </small>
                                                    <p style="margin-top:20px">
                                                      <?php if(strlen($blog->texto) >= 90){echo substr($blog->texto,0 ,90).'...';}else{echo $blog->texto;}  ?>
                                                    </p>
                                                     <div class="why-content-2">
                                                        <?php echo Html::link("blogs/detalle/".$blog->id,"Leer mas",'class="yellow"') ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach ?>
                            </div>
                        </div>
                    </div>
                </div>
            </section>


<?php echo View::partial("plan"); ?>
<?php echo View::partial("footer") ?>
