<div class="Menu_top_bar_area">
    <?php echo View::partial("menu_inicio") ?>
    <div id="menubtn"></div>
    <?php echo View::partial("nav_faq") ?>
</div>


            <section class="home-area" style="margin-top:20px;margin-bottom:20px">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3">
                            <?php echo View::partial("menu_prestamos") ?>
                        </div>
                        <div class="col-md-9">
                             <div class="about-right-content" style="padding-top:20px">
                                <div class="section-title">
                                    <h2>FAQ</h2>
                                </div>
                                <div class="panel-group wow fadeInUp" data-wow-duration="1s" data-wow-delay=".5" id="accordion" role="tablist" aria-multiselectable="true">
                                     <?php $i=1; ?>
                                    <?php foreach ($faq as $value): ?>
                                        
                                     <div class="panel panel-item">
                                        <div class="panel-heading" role="tab" id="headingTwo">
                                            <h4 class="panel-title">
                                                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo<?php echo $i ?>" aria-expanded="false" aria-controls="collapseTwo<?php echo $i ?>">
                                                  <?php echo $value->titulo ?>
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="collapseTwo<?php echo $i ?>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                                            <div class="panel-body">
                                                <?php echo $value->texto ?>
                                            </div>
                                        </div>
                                    </div>
                          
                                    
                                    <?php $i++?>
                                    <?php endforeach ?>


                                   
                               </div> 
                            </div>
                        </div>
                    </div>
                </div> 
            </section>
  

<?php echo View::partial("plan"); ?>
<?php echo View::partial("footer") ?>