<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Corporacion Pacifico</title>
    <link rel="shortcut icon" href="http://localhost:8081/pacifico/img/images/icono.png"/>
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700" rel="stylesheet">
    <?php Tag::css('bootstrap.min') ?>
    <?php Tag::css('jquery-ui') ?>
    <?php Tag::css('font-awesome.min') ?>
    <?php Tag::css('animate') ?>
    <?php Tag::css('slicknav.min') ?>
    <?php Tag::css('myslider') ?>
    <?php Tag::css('magnific-popup') ?>
    <?php Tag::css('slick') ?>
    <?php Tag::css('reset') ?>
    <?php Tag::css('styles') ?>
    <?php Tag::css('responsive') ?>
    <?php echo Tag::js('jquery/jquery.min') ?>
    <?php echo Tag::js('jquery/jquery.kumbiaphp') ?>


    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <?php echo Html::includeCss() ?> 
</head>
<body class="js">
  <div id="preloader"></div>

  
  <?php echo View::content() ?>

  <?php echo Tag::js('js/jquery.min') ?>
  <?php echo Tag::js('combodate') ?><?php echo Tag::js("moment") ?>
  <?php echo Tag::js('js/jquery.easing.1.3') ?>
  <?php echo Tag::js('js/jquery.counterup.min') ?>
  <?php echo Tag::js('js/bootstrap.min') ?>
  <?php echo Tag::js('js/jquery.nav') ?>
  <?php echo Tag::js('js/jquery.sticky') ?>  
  <?php echo Tag::js('js/jquery-ui.min') ?>
  <?php echo Tag::js('js/magnific-popup.min') ?>
  <?php echo Tag::js('js/slick.min') ?>
  <?php echo Tag::js('js/jquery.slicknav.min') ?>
  <?php echo Tag::js('js/active') ?>

</body>
</html>

